name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3 AM UTC
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Add upstream
        run: |
          git remote remove upstream || true
          git remote add upstream https://github.com/rzc0d3r/ESET-KeyGen.git
          git fetch upstream
          git checkout main
          git merge upstream/main --strategy=recursive -X theirs
          git push origin main
